# Generated by Django 6.1 on 2026-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat',
            name='model_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eat',
            name='task_json',
            field=models.JSONField(default=dict),
        ),
    ]
