# Generated by Django 6.1 on 2026-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_alter_eat_model_json_alter_eat_task_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
