# Generated by Django 6.1 on 2026-08-31 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)], verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(500)], verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('coordinates', models.JSONField(blank=True, default={}, null=True, verbose_name='Coordinates')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurant/covers/', verbose_name='Cover image')),
                ('primary_color', models.CharField(default='#111827', max_length=7, verbose_name='Primary color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('waiter', 'Waiter')], default='waiter', max_length=20, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Restaurant staff',
                'verbose_name_plural': 'Restaurant staff',
            },
        ),
    ]
