# Generated by Django 6.1 on 2026-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='coordinates',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Coordinates'),
        ),
    ]
